export const ADD_DATA = 'ADD_DATA'
export const ADD_CURRENT = 'ADD_CURRENT'
export const UPDATE_LAST_FLASH_TIME = 'UPDATE_LAST_FLASH_TIME'

export const ADD_DEVICE = 'ADD_DEVICE'
export const CLEAR = 'CLEAR'

export const SET_DEVICE = 'SET_DEVICE'
export const SET_RATE_TRESHOLD = 'SET_RATE_TRESHOLD'
export const SET_AUTO_CONNECT = 'SET_AUTO_CONNECT'
export const SET_BLE_NAME = 'SET_BLE_NAME'
export const SET_BRAKE_TIME = 'SET_BRAKE_TIME'
export const INCREMENT_FLASH_COUNT = 'INCREMENT_FLASH_COUNT'

export const SET_BLINK_COUNT = 'BLINK_COUNT'
export const SET_REPEAT_INTERVAL = 'SET_REPEAT_INTERVAL'
export const SET_REPEAT_COUNT = 'SET_REPEAT_COUNT'

export const DEFAULTS = 'DEFAULTS'

